name: dict_to_quizlet
dependencies:
    - python==3.7
    - pip
    - pip:
        - Flask
        - Flask-Cors
        - requests
        - lxml
        - argparse
        - tabulate
        - google-api-python-client 
        - google-auth-httplib2 
        - google-auth-oauthlib